# Generated by Django 4.2.4 on 2024-01-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('billing', '0002_clientcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcredentials',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
