# Generated by Django 4.2.4 on 2024-01-02 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('billing', '0003_clientcredentials_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcredentials',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='auth_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='consumer_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='host_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='pass_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='safaricom_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='shortcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='state',
            field=models.ForeignKey(default=uuid.UUID('6c77f2c7-7704-444d-8752-a101bf632b2b'), on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='till_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcredentials',
            name='trx_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='state',
            field=models.ForeignKey(default=uuid.UUID('6c77f2c7-7704-444d-8752-a101bf632b2b'), on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='state',
            field=models.ForeignKey(default=uuid.UUID('6c77f2c7-7704-444d-8752-a101bf632b2b'), on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
