# Generated by Django 4.2.4 on 2024-01-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_clientcredentials_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
