# Generated by Django 4.2.4 on 2024-01-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_clientcredentials_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='transaction_id',
            new_name='receipt_number',
        ),
    ]
