# Generated by Django 4.2.4 on 2024-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_transaction_id_paymenttransaction_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
