# Generated by Django 4.2.4 on 2024-01-08 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(default=uuid.UUID('0d1a604b-c85b-4897-859d-6f39df0bf4d0'), on_delete=django.db.models.deletion.CASCADE, to='base.country'),
        ),
    ]
