# Generated by Django 4.2.4 on 2024-01-02 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('customer', '0002_alter_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(default=uuid.UUID('28a6edd4-1e9c-413a-9422-35da9535cb05'), on_delete=django.db.models.deletion.CASCADE, to='base.country'),
        ),
    ]
