# Generated by Django 4.2.4 on 2024-01-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='state',
        ),
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
